### PR TITLE
Upgrade dependencies to prevent crashes under latest node

### LINKED ISSUE #12: nodejs-npm2arch-0.1.19-1 Cannot find module 'internal/fs'
I got the following backtrace when running `npm2archinstall -h`

```
module.js:472
    throw err;
    ^

Error: Cannot find module 'internal/fs'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at evalmachine.<anonymous>:17:20
    at Object.<anonymous> (/usr/lib/node_modules/npm2arch/node_modules/npm/node_modules/graceful-fs/fs.js:11:8)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (/usr/lib/node_modules/npm2arch/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/npm2arch/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:3:27)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (/usr/lib/node_modules/npm2arch/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at /usr/lib/node_modules/npm2arch/node_modules/npm/lib/npm.js:21:10
    at Object.<anonymous> (/usr/lib/node_modules/npm2arch/node_modules/npm/lib/npm.js:464:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (/usr/lib/node_modules/npm2arch/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/npm2arch/lib/npm2PKGBUILD.coffee:4:9)
    at Object.<anonymous> (/usr/lib/node_modules/npm2arch/lib/npm2PKGBUILD.coffee:95:4)
    at Module._compile (module.js:571:32)
    at Object.loadFile (/usr/lib/node_modules/npm2arch/node_modules/coffee-script/lib/coffee-script/coffee-script.js:182:19)
    at Module.load (/usr/lib/node_modules/npm2arch/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/npm2arch/lib/createPkg.coffee:14:14)
    at Object.<anonymous> (/usr/lib/node_modules/npm2arch/lib/createPkg.coffee:103:4)
    at Module._compile (module.js:571:32)
    at Object.loadFile (/usr/lib/node_modules/npm2arch/node_modules/coffee-script/lib/coffee-script/coffee-script.js:182:19)
    at Module.load (/usr/lib/node_modules/npm2arch/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/npm2arch/bin/npm2archinstall:3:17)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
```

### PR DESCRIPTION
**Pull request by MazeChaZer**
Fixes #12

### CODE REVIEW

**Comment by eelgaev** [comment]
npm is installed globally, why does npm2arch requires it as a dependency after all?

**Comment by lygaret** [comment]
I put together a PKGBUILD to install via this branch, thought you may be interested:

https://gist.github.com/lygaret/f080d12717e50e671a32f3498d1be59f

**Comment by simon04** [comment]
Since 2017-04, the AUR package https://aur.archlinux.org/packages/nodejs-npm2arch/ is now based on the `MazeChaZer:feature/upgrade-dependencies` branch.

**Comment by MazeChaZer** [comment]
Closing as the current AUR package points to https://github.com/simon04/npm2arch

**Pull request closed without merging**
